# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/configuration/ and in linters documentation

VALIDATE_ALL_CODEBASE: false

SPELL_MISSPELL_DISABLE_ERRORS: true

DISABLE_LINTERS:
  - SPELL_CSPELL
  - MARKDOWN_MARKDOWN_LINK_CHECK
  - REPOSITORY_CHECKOV
  - PYTHON_MYPY
  - PYTHON_PYRIGHT
  - MAKEFILE_CHECKMAKE

PYTHON_PYLINT_ARGUMENTS:
  # Disable import check because it needs all the Python dependencies installed in the linter
  # https://github.com/oxsecurity/megalinter/issues/2030
  - "--disable=E0401"
