# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/configuration/ and in linters documentation

VALIDATE_ALL_CODEBASE: false

SPELL_MISSPELL_DISABLE_ERRORS: true

DISABLE_LINTERS:
  - SPELL_CSPELL
  - MARKDOWN_MARKDOWN_LINK_CHECK
  - REPOSITORY_CHECKOV
  - PYTHON_MYPY
  - PYTHON_PYRIGHT
  - MAKEFILE_CHECKMAKE
